# Generated by Django 4.1.dev20211026075023 on 2021-11-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_first_name_account_last_name_account_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='about',
            field=models.TextField(default='', max_length=300),
        ),
    ]
